// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQQnMbmaFcBMLEoknVIponLKvFvm_NNLk',
    appId: '1:774628690099:web:c5d36567e7a914ff8648c6',
    messagingSenderId: '774628690099',
    projectId: 'crypto-8b8cf',
    authDomain: 'crypto-8b8cf.firebaseapp.com',
    storageBucket: 'crypto-8b8cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFJXH7z4MpbR6_tEcwtFWU0wissRO4e4',
    appId: '1:774628690099:android:57917aa247ce26758648c6',
    messagingSenderId: '774628690099',
    projectId: 'crypto-8b8cf',
    storageBucket: 'crypto-8b8cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2UdqsVjvEsOXlqw_-JRMnOBZJ_Fz2UQM',
    appId: '1:774628690099:ios:37b68ff545f5fb0c8648c6',
    messagingSenderId: '774628690099',
    projectId: 'crypto-8b8cf',
    storageBucket: 'crypto-8b8cf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2UdqsVjvEsOXlqw_-JRMnOBZJ_Fz2UQM',
    appId: '1:774628690099:ios:37b68ff545f5fb0c8648c6',
    messagingSenderId: '774628690099',
    projectId: 'crypto-8b8cf',
    storageBucket: 'crypto-8b8cf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
